#!/bin/sh
 filename=$1
 cat ${filename} | while read line
 do
   echo ${line} | sed -E -e "s/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z/`date -u '+%Y-%m-%dT%H:%M:%SZ'`/g"
   sleep 1s
 done
